branches:
  only:
    - master
    - dev

language: cpp

os: linux

dist: bionic

git:
  depth: false

before_install:
  - sudo apt-get -q update

script:
  - mkdir -p build
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=Release ..
  - make fiuncho

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page
  keep_history: true
  allow_empty_commit: true
  local_dir: build/docs/html
  on:
    branch: master

# Build matrix
jobs:
  include:
  # GCC + OpenMPI
  - compiler: gcc
    install:
      - sudo apt-get -y install cmake libopenmpi2 libopenmpi-dev
    after_success: skip
  # GCC + MPICH
  - compiler: gcc
    install:
      - sudo apt-get -y install cmake libmpich12 libmpich-dev
    after_success: skip
  # Clang + OpenMPI
  - compiler: clang
    env:
      - OMPI_CC=clang
      - OMPI_CXX=clang++
    install:
      - sudo apt-get -y install cmake libopenmpi2 libopenmpi-dev
    after_success: skip
  # Clang + MPICH
  - compiler: clang
    env:
      - MPICH_CC=clang
      - MPICH_CXX=clang++
    install:
      - sudo apt-get -y install cmake libmpich12 libmpich-dev
    after_success: skip
  # Docs build and deploy
  - install:
      - sudo apt-get -y install cmake python3-sphinx python3-breathe doxygen
    script:
      - mkdir -p build
      - cd build
      - cmake -D CMAKE_BUILD_TYPE=Release ..
      - make docs